<?php


if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_flexible-content',
		'title' => 'Flexible Content',
		'fields' => array (
			array (
				'key' => 'field_5422a3a4a988b',
				'label' => 'Inhaltsblöcke',
				'name' => 'flexible-content',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Rasteransicht',
						'name' => 'flexible-content-grid',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_54250d8f47e0f',
								'label' => 'Rasterbreite',
								'name' => 'flexible-content-grid-size',
								'type' => 'select',
								'instructions' => 'Wählen Sie hier aus, wie breit das Raster werden soll.',
								'column_width' => '',
								'choices' => array (
									'two-columns' => 'Zwei Spalten',
									'three-columns' => 'Drei Spalten',
									'four-columns' => 'Vier Spalten',
								),
								'default_value' => 'three-columns : Drei Spalten',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5422b3e289a41',
								'label' => 'Rasterelemente',
								'name' => 'flexible-content-grid-entry',
								'type' => 'relationship',
								'column_width' => '',
								'return_format' => 'object',
								'post_type' => array (
									0 => 'post',
									1 => 'page',
									2 => 'veranstaltung',
									3 => 'selbsthilfegruppe',
									4 => 'fachbereich',
									5 => 'produkt',
									6 => 'jobs',
									7 => 'standorte',
								),
								'taxonomy' => array (
									0 => 'all',
									1 => 'category:1',
									2 => 'category:2',
									3 => 'category:57',
									4 => 'themen:95',
									5 => 'themen:38',
									6 => 'themen:14',
									7 => 'themen:34',
									8 => 'themen:97',
									9 => 'themen:4',
									10 => 'themen:100',
									11 => 'themen:102',
									12 => 'themen:104',
									13 => 'themen:95',
									14 => 'themen:38',
									15 => 'themen:14',
									16 => 'themen:34',
									17 => 'themen:97',
									18 => 'themen:4',
									19 => 'themen:100',
									20 => 'themen:102',
									21 => 'themen:104',
									22 => 'selbsthilfegruppe-kategorie:114',
									23 => 'selbsthilfegruppe-kategorie:26',
									24 => 'selbsthilfegruppe-kategorie:115',
									25 => 'selbsthilfegruppe-kategorie:116',
									26 => 'produkt-kategorie:4',
									27 => 'produkt-kategorie:5',
									28 => 'produkt-kategorie:6',
									29 => 'produkt-kategorie:7',
									30 => 'produkt-kategorie:8',
									31 => 'produkt-kategorie:9',
									32 => 'produkt-kategorie:10',
									33 => 'produkt-kategorie:11',
									34 => 'produkt-kategorie:12',
									35 => 'produkt-kategorie:13',
									36 => 'produkt-kategorie:14',
									37 => 'produkt-kategorie:15',
									38 => 'produkt-kategorie:16',
									39 => 'produkt-kategorie:17',
									40 => 'produkt-kategorie:18',
									41 => 'produkt-kategorie:19',
									42 => 'produkt-kategorie:20',
									43 => 'produkt-kategorie:21',
									44 => 'produkt-kategorie:22',
									45 => 'produkt-kategorie:23',
									46 => 'produkt-kategorie:24',
									47 => 'produkt-kategorie:25',
									48 => 'produkt-kategorie:26',
									49 => 'produkt-kategorie:27',
									50 => 'produkt-kategorie:28',
									51 => 'produkt-kategorie:29',
									52 => 'produkt-kategorie:30',
									53 => 'produkt-kategorie:31',
									54 => 'produkt-kategorie:32',
									55 => 'produkt-kategorie:33',
									56 => 'produkt-kategorie:34',
									57 => 'produkt-kategorie:35',
									58 => 'produkt-kategorie:36',
									59 => 'produkt-kategorie:37',
									60 => 'produkt-kategorie:38',
									61 => 'produkt-kategorie:39',
									62 => 'produkt-kategorie:40',
									63 => 'produkt-kategorie:41',
									64 => 'produkt-kategorie:42',
									65 => 'produkt-kategorie:43',
									66 => 'produkt-kategorie:52',
									67 => 'themen:95',
									68 => 'themen:38',
									69 => 'themen:14',
									70 => 'themen:34',
									71 => 'themen:97',
									72 => 'themen:4',
									73 => 'themen:100',
									74 => 'themen:102',
									75 => 'themen:104',
									76 => 'job-kategorien:47',
									77 => 'job-kategorien:48',
									78 => 'job-kategorien:106',
									79 => 'standort-kategorien:49',
									80 => 'standort-kategorien:50',
									81 => 'standort-kategorien:51',
									82 => 'standort-kategorien:107',
									83 => 'standort-kategorien:108',
									84 => 'standort-kategorien:109',
									85 => 'standort-kategorien:110',
									86 => 'standort-kategorien:111',
									87 => 'standort-kategorien:112',
									88 => 'standort-kategorien:113',
								),
								'filters' => array (
									0 => 'search',
									1 => 'post_type',
								),
								'result_elements' => array (
									0 => 'featured_image',
									1 => 'post_type',
									2 => 'post_title',
								),
								'max' => '',
							),
						),
					),
					array (
						'label' => 'Nur Text',
						'name' => 'flexible-content-text',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_544f6d5cbe9a6',
								'label' => 'Textinhalte',
								'name' => 'flexible-content-text-content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Text mit Bild',
						'name' => 'flexible-content-hybrid',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_544f6db0be9a8',
								'label' => 'Ausrichtung',
								'name' => 'flexible-content-hybrid-flow',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'left' => 'Linksbündig',
									'right' => 'Rechtsbündig',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_544f6deabe9a9',
								'label' => 'Bildelement',
								'name' => 'flexible-content-hybrid-img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_544f6e15be9aa',
								'label' => 'Textelement',
								'name' => 'flexible-content-hybrid-txt',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Text mit Infobox',
						'name' => 'flexible-content-info',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5422b45a89a43',
								'label' => 'Textbereich',
								'name' => 'flexible-content-info-main',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_5422b47289a44',
								'label' => 'Infobox',
								'name' => 'flexible-content-info-aside',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_5422b48b89a45',
								'label' => 'Weiterführender Link',
								'name' => 'flexible-content-info-link',
								'type' => 'page_link',
								'column_width' => '',
								'post_type' => array (
									0 => 'post',
									1 => 'page',
									2 => 'produkt',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5422b4b589a46',
								'label' => 'Text weiterführender Link',
								'name' => 'flexible-content-info-link-text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Aufmacher mit Bild – Groß',
						'name' => 'flexible-content-hero-big',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5424289508b6a',
								'label' => 'Aufmacher – Headline',
								'name' => 'flexible-content-hero-big-headline',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_542428bc08b6b',
								'label' => 'Aufmacher – Bild',
								'name' => 'flexible-content-hero-big-img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_542428d708b6c',
								'label' => 'Aufmacher – Text',
								'name' => 'flexible-content-hero-big-txt',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_542429e908b71',
								'label' => 'Aufmacher – Link',
								'name' => 'flexible-content-hero-big-link',
								'type' => 'page_link',
								'column_width' => '',
								'post_type' => array (
									0 => 'post',
									1 => 'page',
									2 => 'produkt',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
					),
					array (
						'label' => 'Aufmacher mit Bild – Mittel',
						'name' => 'flexible-content-hero-med',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_54366cae74299',
								'label' => 'Aufmacher-Zeile',
								'name' => 'flexible-content-hero-med-row',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_54366d08eab01',
										'label' => 'Aufmacher – Headline',
										'name' => 'flexible-content-hero-med-headline',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_54366d27eab02',
										'label' => 'Aufmacher – Bild',
										'name' => 'flexible-content-hero-med-img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_54366d43eab03',
										'label' => 'Aufmacher – Text',
										'name' => 'flexible-content-hero-med-txt',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'br',
									),
									array (
										'key' => 'field_54366d59eab04',
										'label' => 'Aufmacher – Link',
										'name' => 'flexible-content-hero-med-link',
										'type' => 'page_link',
										'column_width' => '',
										'post_type' => array (
											0 => 'post',
											1 => 'page',
											2 => 'veranstaltung',
											3 => 'produkt',
											4 => 'jobs',
											5 => 'standorte',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Neue Zeile.',
							),
						),
					),
					array (
						'label' => 'Kalender',
						'name' => 'flexible-content-event',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_54af884441393',
								'label' => 'Kalenderüberschrift',
								'name' => 'flexible-content-event-headline',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_54ae9c1ed0f31',
								'label' => 'Kalendereinträge',
								'name' => 'flexible-content-event-list',
								'type' => 'relationship',
								'column_width' => '',
								'return_format' => 'object',
								'post_type' => array (
									0 => 'veranstaltung',
								),
								'taxonomy' => array (
									0 => 'all',
								),
								'filters' => array (
									0 => 'search',
								),
								'result_elements' => array (
									0 => 'featured_image',
									1 => 'post_type',
									2 => 'post_title',
								),
								'max' => '',
							),
						),
					),
					array (
						'label' => 'Produktliste',
						'name' => 'flexible-content-products',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_54ae9ef51046b',
								'label' => 'Einträge Produktliste',
								'name' => 'flexible-content-product-list',
								'type' => 'relationship',
								'column_width' => '',
								'return_format' => 'object',
								'post_type' => array (
									0 => 'produkt',
								),
								'taxonomy' => array (
									0 => 'all',
								),
								'filters' => array (
									0 => 'search',
								),
								'result_elements' => array (
									0 => 'featured_image',
									1 => 'post_type',
									2 => 'post_title',
								),
								'max' => '',
							),
						),
					),
				),
				'button_label' => 'Neuer Inhaltsblock.',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '!=',
					'value' => '_templates/_template-downloads.php',
					'order_no' => 1,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '!=',
					'value' => '_templates/_template-links.php',
					'order_no' => 2,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '!=',
					'value' => '_templates/_template-agb.php',
					'order_no' => 3,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'fachbereich',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'custom_fields',
				1 => 'discussion',
				2 => 'comments',
				3 => 'format',
				4 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
